version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: ${BACK_INTERNAL_PORT}
      ENV: ${ENV}
      DB_HOST: db
      DB_PORT: ${DB_INTERNAL_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_TIME: ${JWT_EXPIRE_TIME}
      TEST_DB_PORT: ${TEST_DB_PORT}
      S3_KEY: ${S3_KEY}
      S3_SECRET: ${S3_SECRET}
      S3_BUCKET: ${S3_BUCKET}
      S3_HOST: ${S3_HOST}
      UI_HOST: http://localhost:8088
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      NOTIFICATION_CHANEL: ${NOTIFICATION_CHANEL}
      SOCKET_PORT: ${SOCKET_PORT}
    ports:
      - ${BACK_EXTERNAL_PORT}:${BACK_INTERNAL_PORT}
      - ${SOCKET_PORT}:${SOCKET_PORT}
    depends_on:
      - db
      - redis-stack
      - minio

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - ${UI_PORT}:80
    environment:
      API_BASE_URL: http://localhost:${BACK_EXTERNAL_PORT}
      API_SOCKET_URL: http://localhost:${SOCKET_PORT}
    command: >
      sh -c 'sed -i \
         "s|PLACEHOLDER_API_BASE_URL|$$API_BASE_URL|g; \
          s|PLACEHOLDER_API_SOCKET_URL|$$API_SOCKET_URL|g" \
         /usr/share/nginx/html/index.html && nginx -g "daemon off;"'

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - ./local-minio-data:/data

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped


  db-test:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${TEST_DB_PORT}:5432

volumes:
  postgres_data: