version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: ${BACK_INTERNAL_PORT}
      ENV: ${ENV}
      DB_HOST: db
      DB_PORT: ${DB_INTERNAL_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_TIME: ${JWT_EXPIRE_TIME}
      TEST_DB_PORT: ${TEST_DB_PORT}
      UI_HOST: http://localhost:8088
    ports:
      - ${BACK_EXTERNAL_PORT}:${BACK_INTERNAL_PORT}
    depends_on:
      - db

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - ${UI_PORT}:80
    environment:
      API_BASE_URL: http://localhost:${BACK_EXTERNAL_PORT}
    command: >
      sh -c 'sed -i "s|PLACEHOLDER_API_BASE_URL|$$API_BASE_URL|g" /usr/share/nginx/html/index.html && nginx -g "daemon off;"'

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${TEST_DB_PORT}:5432

volumes:
  postgres_data: