version: '3.8'

services:
  ice-bank-backend:
    image: ghcr.io/xaosaki/ice-bank-backend:latest
    environment:
      ENV: ${ENV}
      DB_HOST: ${ICE_DB_HOST}
      DB_PORT: ${DB_INTERNAL_PORT}
      DB_USERNAME: ${ICE_DB_USERNAME}
      DB_PASSWORD: ${ICE_DB_PASSWORD}
      DB_NAME: ${ICE_DB_NAME}
      JWT_SECRET: ${ICE_JWT_SECRET}
      JWT_EXPIRE_TIME: ${ICE_JWT_EXPIRE_TIME}
      UI_HOST: https://ice.xaosaki.pro
      S3_KEY: ${S3_KEY}
      S3_SECRET: ${S3_SECRET}
      S3_BUCKET: ${S3_BUCKET}
      S3_HOST: ${S3_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      NOTIFICATION_CHANEL: ${NOTIFICATION_CHANEL}
      SOCKET_PORT: ${SOCKET_PORT}
    restart: unless-stopped
    networks:
      - xaosakipro_default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.ice-api.rule=Host(`ice-api.xaosaki.pro`)"
      - "traefik.http.routers.ice-api.entrypoints=websecure"
      - "traefik.http.routers.ice-api.tls=true"
      - "traefik.http.routers.ice-api.tls.certresolver=prod"
      - "traefik.http.services.ice-api.loadbalancer.server.port=3000"

  ice-bank-frontend:
    image: ghcr.io/xaosaki/ice-bank-frontend:latest
    container_name: ice_bank_frontend
    environment:
      API_BASE_URL: https://ice-api.xaosaki.pro
    command: >
      sh -c 'sed -i "s|PLACEHOLDER_API_BASE_URL|$$API_BASE_URL|g" /usr/share/nginx/html/index.html && nginx -g "daemon off;"'
    restart: unless-stopped
    networks:
      - xaosakipro_default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.ice.rule=Host(`ice.xaosaki.pro`)"
      - "traefik.http.routers.ice.entrypoints=websecure"
      - "traefik.http.routers.ice.tls=true"
      - "traefik.http.routers.ice.tls.certresolver=prod"
      - "traefik.http.services.ice.loadbalancer.server.port=80"

networks:
  xaosakipro_default:
    external: true